### ISSUE TITLE
dashboard crash

### ISSUE THREAD

**Issue by mcollina** [vidi-insights/vidi-dashboard#135] opened 2016-02-14 11:45 UTC
Not sure if this is s toolbag issue or a vidi issue.. cc @cjihrig 

```js
/Users/matteo/Repositories/vidi-dashboard/node_modules/toolbag/lib/client.js:68
    message = JSON.stringify(message);
                   ^

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Client.report (/Users/matteo/Repositories/vidi-dashboard/node_modules/toolbag/lib/client.js:68:20)
    at reportInterval [as _repeat] (/Users/matteo/Repositories/vidi-dashboard/node_modules/toolbag/lib/reporter.js:124:18)
    at wrapper [as _onTimeout] (timers.js:275:19)
    at Timer.unrefdHandle (timers.js:312:14)
```

**Comment by mcdonnelldean** [comment] 2016-02-14 12:41
Note to self, caused by logging.

**Comment by mcdonnelldean** [comment] 2016-02-14 13:26
@mcollina Did the tagging branch fix this?

**Comment by mcollina** [comment] 2016-02-14 16:04
Yes.

**Comment by mcollina** [comment] 2016-02-14 16:05
But it got worse:

```
Error: [TIMEOUT:ppes40ttbikh/nkc7ef6obu3h:500<1455457010517-1455457010011:undefined]
    at null._onTimeout (/Users/matteo/Repositories/vidi-dashboard/node_modules/seneca/node_modules/gate-executor/gate-executor.js:111:21)
    at Timer.listOnTimeout (timers.js:92:15)
Error: [TIMEOUT:1o1yztd0t7ok/7ktom9a3lxvl:500<1455457010525-1455457010012:undefined]
    at null._onTimeout (/Users/matteo/Repositories/vidi-dashboard/node_modules/seneca/node_modules/gate-executor/gate-executor.js:111:21)
    at Timer.listOnTimeout (timers.js:92:15)


Seneca Fatal Error
==================

Message: seneca: Action hook:sink,role:metrics failed: [TIMEOUT:ka9zs89ecqh9/mgyr2bzgruim:500<1455457010526-1455457010012:undefined].

Code: act_execute

Details: { id: 'ka9zs89ecqh9/mgyr2bzgruim',
  gate: false,
  ungate: true,
  desc: undefined,
  cb: [Function: noop],
  fn: [Function: handle_storage],
  time: { start: 1455457010012, end: 1455457010526 },
  'orig$': { [Error: [TIMEOUT:ka9zs89ecqh9/mgyr2bzgruim:500<1455457010526-1455457010012:undefined]] timeout: true },
  'message$': '[TIMEOUT:ka9zs89ecqh9/mgyr2bzgruim:500<1455457010526-1455457010012:undefined]',
  message: '[TIMEOUT:ka9zs89ecqh9/mgyr2bzgruim:500<1455457010526-1455457010012:undefined]',
  pattern: 'hook:sink,role:metrics',
  instance: 'Seneca/1.1.0/vpihia5g5pxq/1455454297606/88378/-',
  plugin: {} }

Stack:
    at null._onTimeout (/Users/matteo/Repositories/vidi-dashboard/node_modules/seneca/node_modules/gate-executor/gate-executor.js:111:21)
    at Timer.listOnTimeout (timers.js:92:15)

Instance: Seneca/1.1.0/vpihia5g5pxq/1455454297606/88378/-
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see senecajs.org/fatal.html)
    at act_done (/Users/matteo/Repositories/vidi-dashboard/node_modules/seneca/seneca.js:1196:29)

When: 2016-02-14T13:36:50.534Z

Log: [sys,seneca,1.1.0,vpihia5g5pxq/1455454297606/88378/-,act_execute,seneca: Action hook:sink,role:metrics failed:

Node:
  { http_parser: '2.5.0', node: '4.2.4', v8: '4.5.103.35', uv: '1.7.5', zlib: '1.2.8', ares: '1.10.1-DEV', icu: '56.1', modules: '46', openssl: '1.0.2e' },
  { debug: false, uv: true, ipv6: true, tls_npn: true, tls_sni: true, tls_ocsp: true, tls: true },
  [ 'Binding contextify', 'Binding natives', 'NativeModule events', 'NativeModule buffer', 'Binding buffer', 'NativeModule internal/util', 'NativeModule timers', 'Binding timer_wrap', 'NativeModule _linklist', 'NativeModule assert', 'NativeModule util', 'Binding uv', 'Binding util', 'NativeModule path', 'NativeModule module', 'NativeModule internal/module', 'NativeModule vm', 'NativeModule fs', 'Binding fs', 'NativeModule constants', 'Binding constants', 'NativeModule stream', 'NativeModule _stream_readable', 'NativeModule _stream_writable', 'NativeModule _stream_duplex', 'NativeModule _stream_transform', 'NativeModule _stream_passthrough', 'Binding fs_event_wrap', 'NativeModule os', 'Binding os', 'NativeModule crypto', 'Binding crypto', 'NativeModule internal/streams/lazy_transform', 'NativeModule string_decoder', 'NativeModule net', 'Binding cares_wrap', 'Binding tty_wrap', 'Binding tcp_wrap', 'Binding pipe_wrap', 'Binding stream_wrap', 'NativeModule dns', 'NativeModule url', 'NativeModule punycode', 'NativeModule querystring', 'NativeModule http', 'NativeModule _http_incoming', 'NativeModule _http_common', 'NativeModule internal/freelist', 'Binding http_parser', 'NativeModule _http_outgoing', 'NativeModule _http_server', 'NativeModule _http_agent', 'NativeModule _http_client', 'NativeModule https', 'NativeModule tls', 'NativeModule _tls_common', 'NativeModule _tls_wrap', 'NativeModule _stream_wrap', 'Binding js_stream', 'Binding tls_wrap', 'NativeModule _tls_legacy', 'NativeModule zlib', 'Binding zlib', 'NativeModule tty', 'Binding signal_wrap', 'NativeModule dgram', 'Binding udp_wrap', 'NativeModule console', 'NativeModule cluster', 'NativeModule child_process', 'Binding spawn_sync', 'NativeModule internal/child_process', 'Binding process_wrap', 'NativeModule internal/socket_list', 'NativeModule internal/cluster', 'NativeModule domain' ]
```

**Comment by mcdonnelldean** [comment] 2016-02-14 16:21
So this is because of the influx sink which lacks batching. Its not leeping up with the per second emitting of metrics. I'm nearly done with a batching PR that will fix this

**Comment by mcdonnelldean** [comment] 2016-02-15 00:53
Cheers,

I have a fix for this in the influx sink incoming in the morning.

Kindest Regards,

Dean

**Closed** 2016-02-15 16:30 UTC
Labels: bug
